version: '3'

services:
  web:
    build: 
      context: ./web
      args:
        - POSTGRES_DB=$POSTGRES_DB
        - POSTGRES_USER=$POSTGRES_USER
        - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/web_django
    restart: always
    ports:
      - '8000:8000'
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
    restart: always
